apiVersion: 1

datasources:
  - name: Followers
    uid: csv-followers
    type: marcusolsson-csv-datasource
    editable: true
    url: /data/followers_diff.csv
    jsonData:
      storage: local
  - name: Friends
    uid: csv-friends
    type: marcusolsson-csv-datasource
    editable: true
    url: /data/friends_diff.csv
    jsonData:
      storage: local
